public class wexample {
    public list<Wraperclassexample> wacc	{set;get;}
    public string name						{set;get;}
    Public string phone						{set;get;}
    public list<Account> acclist			{set;get;}
    public Wraperclassexample wa	{set;get;}
    
    public Wexample(){
        wacc=new list<Wraperclassexample>();
        wa=new Wraperclassexample();
    
        
        wa.acc.name= 'baji';
        wa.acc.phone='8888';
        wa.check=false;
        wacc.add(wa);
        
        
    
    
    }
}